### ISSUE TITLE
P-ROC demo / template task list...

### ISSUE THREAD

**Issue by horseyhorsey** [FlippingFlips/pingod-addons#3]
#### Documentation

* [x] Documentation

#### Game Demo

* [x] PinGod game running P-ROC (netproc) with some modes, switch handling.

#### Simulation - Visual Pinball

* [x] Create table and provide assets like MoonStation demo to create playfield images, decals, inserts
* [x] Link game with the `pingod-controller-com`
* [ ] With Lamps example
* [x] With Leds example
* [ ] Make working with original P-ROC board, different machine configs. Like WPC, DATA EAST, STERN
